create table if not exists users (
  id bigint generated by default as identity primary key,
  email varchar(255) not null unique,
  password_hash varchar(255) not null,
  role varchar(50) not null default 'USER',
  created_at timestamp not null default current_timestamp
);
