CREATE TABLE recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_recipes_user FOREIGN KEY (user_id) REFERENCES users(id)
);